[General]
__userfile__=true
window_manager=openbox

[Environment]
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0
QT_QPA_PLATFORMTHEME=qt6ct

[Keyboard]
layout=us
model=pc105
variant=

[Touchpad]
ETPS%252F2%2520Elantech%2520Touchpad\accelSpeed=nan
ETPS%252F2%2520Elantech%2520Touchpad\disableWhileTypingEnabled=-1
ETPS%252F2%2520Elantech%2520Touchpad\dragLockEnabled=-1
ETPS%252F2%2520Elantech%2520Touchpad\naturalScrollingEnabled=-1
ETPS%252F2%2520Elantech%2520Touchpad\scrollingMethodEnabled=0
ETPS%252F2%2520Elantech%2520Touchpad\tapToDragEnabled=-1
ETPS%252F2%2520Elantech%2520Touchpad\tappingEnabled=-1
ETPS%252F2%2520Elantech%2520TrackPoint\accelSpeed=0
ETPS%252F2%2520Elantech%2520TrackPoint\disableWhileTypingEnabled=-1
ETPS%252F2%2520Elantech%2520TrackPoint\dragLockEnabled=-1
ETPS%252F2%2520Elantech%2520TrackPoint\naturalScrollingEnabled=0
ETPS%252F2%2520Elantech%2520TrackPoint\scrollingMethodEnabled=4
ETPS%252F2%2520Elantech%2520TrackPoint\tapToDragEnabled=-1
ETPS%252F2%2520Elantech%2520TrackPoint\tappingEnabled=-1
